name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22.12.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x
          include-prerelease: true

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build Roslyn host
        run: dotnet build src/Nika.Host
